baseURL = "https://blog.oak-means.com/"
languageCode = "en-ie"
title = "OaK-means web log"
theme = "hugo-nederburg-theme"
# Unmark to use post folder for images. Default is static folder.
#usepostimgfolder = true
slogan = "semantic arguments"
description = "Weblog of the oaK-means project" # meta description
# You need to set author to have an author bio. If you have a writer in the markdown file it will override this.
author = "Invisible Architects"
authorLink = "https://invisiblearchitects.com"
bio = [
    "An invisible architects project"
]
copyright = [
          "&copy; 2020 John Kavanagh",
          "Nederburg Hugo Theme by [Appernetic](https://appernetic.io).",
]


[build]
publish = "public"
command = "hugo"

[context.production.environment]
HUGO_VERSION = "0.52"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"



[params]

email = "glassofwater@oak-means.com"

  # Nav links in the side bar
  [[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

  [[menu.main]]
  name = "About"
  url = "about/"
  weight = 2

  [[menu.main]]
  name = "Get in touch"
  url = "contact/"
  weight = 3

# this will also be in author bio if there is no writer.
  [params.social]
  email         = "glassofwater@oak-means.com"
#  twitter       = "full profile url in twitter"
#  instagram     = "full profile url in instagram"
  github        = "full profile url in github"
  rss           = true

